name: ğŸ“„ Hugo GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸš€ Git checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: ğŸ”„ Update theme
        uses: snickerbockers/submodules-init@v4

      - name: âš™ï¸ Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.110.0'

      - name: ğŸ—ï¸ Build with Hugo
        run: hugo --minify

      - name: ğŸ“¦ Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN  }}
          publish_dir: ./public
